// Generated by scripts/generate-react-icons.mjs. Do not edit manually.
import type {
  ForwardRefExoticComponent,
  HTMLAttributes,
  RefAttributes,
} from "react";

export const materialSymbolNames: readonly [
  "account_balance",
  "account_balance_wallet",
  "add",
  "add_circle",
  "analytics",
  "apps",
  "archive",
  "arrow_back",
  "arrow_back_ios",
  "arrow_back_ios_new",
  "arrow_circle_down",
  "arrow_circle_left",
  "arrow_circle_right",
  "arrow_circle_up",
  "arrow_downward",
  "arrow_forward",
  "arrow_upward",
  "attach_file",
  "backpack",
  "badge",
  "bar_chart",
  "bolt",
  "book_2",
  "business_center",
  "calendar_month",
  "call",
  "cancel",
  "chat",
  "chat_add_on",
  "check",
  "check_circle",
  "chevron_left",
  "chevron_right",
  "close",
  "cloud",
  "content_copy",
  "credit_card",
  "currency_exchange",
  "dark_mode",
  "database",
  "delete",
  "description",
  "dock_to_left",
  "download",
  "drag_indicator",
  "edit",
  "error",
  "event",
  "expand_less",
  "expand_more",
  "favorite",
  "file_open",
  "filter_list",
  "flag",
  "folder",
  "folder_open",
  "grid_view",
  "help",
  "home",
  "info",
  "keyboard_arrow_down",
  "keyboard_arrow_left",
  "keyboard_arrow_right",
  "keyboard_arrow_up",
  "language",
  "light_mode",
  "link",
  "location_on",
  "lock",
  "login",
  "logout",
  "mail",
  "menu",
  "mic",
  "more_horiz",
  "more_vert",
  "navigation",
  "notifications",
  "notifications_off",
  "open_in_new",
  "palette",
  "person",
  "photo_camera",
  "play_arrow",
  "progress_activity",
  "public",
  "qr_code_scanner",
  "radio_button_checked",
  "radio_button_unchecked",
  "refresh",
  "remove",
  "remove_circle",
  "save",
  "schedule",
  "search",
  "send",
  "settings",
  "share",
  "shield",
  "shopping_cart",
  "star",
  "sync",
  "terminal",
  "thumb_down",
  "thumb_up",
  "tune",
  "unfold_more",
  "upload",
  "verified",
  "visibility",
  "visibility_off",
  "warning",
  "workspace_premium"
];

export type MaterialSymbolName = (typeof materialSymbolNames)[number];
export type MaterialSymbolBaseProps = Omit<HTMLAttributes<HTMLSpanElement>, "children"> & {
  size?: number | string;
  fill?: boolean | 0 | 1;
  weight?: number;
  grade?: number;
  opticalSize?: number;
};
export type MaterialSymbolProps = MaterialSymbolBaseProps & {
  name: MaterialSymbolName;
};
export type MaterialSymbolComponent = ForwardRefExoticComponent<
  MaterialSymbolBaseProps & RefAttributes<HTMLSpanElement>
>;

export const MaterialSymbol: ForwardRefExoticComponent<
  MaterialSymbolProps & RefAttributes<HTMLSpanElement>
>;
export const Icon: typeof MaterialSymbol;
export function createMaterialSymbol(
  name: MaterialSymbolProps["name"],
  displayName?: string,
): MaterialSymbolComponent;

export const materialSymbolComponents: Readonly<
  Record<MaterialSymbolName, MaterialSymbolComponent>
>;

export const iconNames: typeof materialSymbolNames;
export type IconName = MaterialSymbolName;
export type IconBaseProps = MaterialSymbolBaseProps;
export type IconProps = MaterialSymbolProps;
export type IconComponent = MaterialSymbolComponent;
export const iconComponents: typeof materialSymbolComponents;
export function getIconComponent(name: MaterialSymbolName): MaterialSymbolComponent;
export function getIconComponent(name: string): MaterialSymbolComponent | undefined;

export const IconArrowBackIos: MaterialSymbolComponent;
export const IconArrowBackIosNew: MaterialSymbolComponent;
export const IconArrowDown: MaterialSymbolComponent;
export const IconArrowLeft: MaterialSymbolComponent;
export const IconArrowRight: MaterialSymbolComponent;
export const IconArrowUp: MaterialSymbolComponent;
export const IconBell: MaterialSymbolComponent;
export const IconChart: MaterialSymbolComponent;
export const IconCheck: MaterialSymbolComponent;
export const IconChevronDown: MaterialSymbolComponent;
export const IconChevronLeft: MaterialSymbolComponent;
export const IconChevronRight: MaterialSymbolComponent;
export const IconChevronSelect: MaterialSymbolComponent;
export const IconChevronUp: MaterialSymbolComponent;
export const IconCircle: MaterialSymbolComponent;
export const IconCircleAlert: MaterialSymbolComponent;
export const IconCircleCheck: MaterialSymbolComponent;
export const IconCircleClose: MaterialSymbolComponent;
export const IconCircleInfo: MaterialSymbolComponent;
export const IconClock: MaterialSymbolComponent;
export const IconCross: MaterialSymbolComponent;
export const IconLoader: MaterialSymbolComponent;
export const IconMenu: MaterialSymbolComponent;
export const IconMinus: MaterialSymbolComponent;
export const IconMoon: MaterialSymbolComponent;
export const IconMore: MaterialSymbolComponent;
export const IconPlus: MaterialSymbolComponent;
export const IconQrCode: MaterialSymbolComponent;
export const IconSearch: MaterialSymbolComponent;
export const IconSidebar: MaterialSymbolComponent;
export const IconSun: MaterialSymbolComponent;
export const IconSwap: MaterialSymbolComponent;
export const IconVisibilityOff: MaterialSymbolComponent;
export const IconWallet: MaterialSymbolComponent;
